kind = "web"
previewPath = "/"
title = "BirrStream"
version = "1.0.0"
id = "artifacts/birrstream"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 21707

[services.development]
run = "pnpm --filter @workspace/birrstream run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/birrstream", "run", "build" ]
publicDir = "artifacts/birrstream/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "21707"
BASE_PATH = "/"
